### ISSUE TITLE
[vscode] Add new chat provider: Skype

### ISSUE THREAD

**Issue by vicbirky** [karigari/vscode-chat#140] opened 2018-09-19 23:55 UTC
My chat provider is Skype

- Extension Version: 0.5.11
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0-insider

**Comment by arjun27** [comment] 2018-10-09 15:28
closing as duplicate of #121

**Closed by arjun27** 2018-10-09 15:28 UTC
