### ISSUE TITLE
[vscode] Add new chat provider: Microsoft Teams

### ISSUE THREAD

**Issue by jallen31** [karigari/vscode-chat#212] opened 2018-10-02 18:34 UTC
My chat provider is Microsoft Teams

- Extension Version: 0.6.2
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.27.2

**Comment by chase9** [comment] 2018-10-09 14:53
Duplicate of #18

**Closed** 2018-10-09 15:13 UTC
