### ISSUE TITLE
[vscode] Add new chat provider: Mattermost

### ISSUE THREAD

**Issue by fluxynet** [karigari/vscode-chat#162] opened 2018-09-24 07:17 UTC
My chat provider is Mattermost

- Extension Version: 0.6.1
- OS Version: Linux x64 4.18.7-1-default
- VSCode version: 1.27.1

**Comment by arjun27** [comment] 2018-10-09 15:04
closing as duplicate of #118

**Closed by arjun27** 2018-10-09 15:04 UTC
