### ISSUE TITLE
[vscode] Add new chat provider: Telegram

### ISSUE THREAD

**Issue by yuk7hi** [karigari/vscode-chat#185] opened 2018-09-26 17:33 UTC
My chat provider is Telegram

- Extension Version: 0.6.1
- OS Version: Linux x64 4.15.0-34-generic
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:02
closing as duplicate of #68

**Closed by arjun27** 2018-10-09 15:02 UTC
