### ISSUE TITLE
[vscode] Add new chat provider: Microsoft Teams

### ISSUE THREAD

**Issue by jamesmenera** [karigari/vscode-chat#137] opened 2018-09-18 20:51 UTC
My chat provider is Microsoft Teams

- Extension Version: 0.5.9
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-09-28 09:50
thanks @jamesmenera  - Will close this issue as duplicate of #18 and track it there

**Closed** 2018-09-28 09:51 UTC
