### ISSUE TITLE
[vscode] Add new chat provider: Rocket.Chat

### ISSUE THREAD

**Issue by aanguss** [karigari/vscode-chat#187] opened 2018-09-26 17:56 UTC
My chat provider is Rocket.Chat

- Extension Version: 0.6.1
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.28.0-insider

**Comment by arjun27** [comment] 2018-10-09 15:04
closing as duplicate of #9

**Closed by arjun27** 2018-10-09 15:04 UTC
