### ISSUE TITLE
[vscode] Add new chat provider: Webex Teams

### ISSUE THREAD

**Issue by nckbgov** [karigari/vscode-chat#201] opened 2018-09-28 09:37 UTC
My chat provider is Webex Teams

- Extension Version: 0.6.2
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:21
closing as duplicate of #188

**Closed by arjun27** 2018-10-09 15:21 UTC
