### ISSUE TITLE
[vscode] Add new chat provider: skype

### ISSUE THREAD

**Issue by chhschou** [karigari/vscode-chat#199] opened 2018-09-28 08:53 UTC
My chat provider is skype

- Extension Version: 0.6.1
- OS Version: Linux x64 4.18.8-041808-generic
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:28
closing as duplicate of #121

**Closed by arjun27** 2018-10-09 15:28 UTC
