### ISSUE TITLE
[vscode] Add new chat provider: Microsoft Teams

### ISSUE THREAD

**Issue by aelking** [karigari/vscode-chat#147] opened 2018-09-20 15:39 UTC
My chat provider is Microsoft Teams

- Extension Version: 0.5.11
- OS Version: Windows_NT x64 10.0.17763
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-09-28 09:49
thanks @aelking - Will close this issue as duplicate of #18 and track it there

**Closed by arjun27** 2018-09-28 09:49 UTC
