### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by NathanBaudin** [karigari/vscode-chat#373] opened 2019-04-27 09:44 UTC
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.13.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/nathanbaudin/karigari.chat-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment] 2019-04-28 02:57
Duplicate of #291

**Closed by arjun27** 2019-04-28 02:57 UTC
