### ISSUE TITLE
[vscode] Add new chat provider: Microsoft Teams

### ISSUE THREAD

**Issue by ChaplinMarchais** [karigari/vscode-chat#111] opened 2018-09-10 12:34 UTC
My chat provider is Microsoft Teams

- Extension Version: 0.5.9
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.27.1

**Comment by arjun27** [comment] 2018-09-28 09:37
thanks @ChaplinMarchais  - Will close this issue as duplicate of #18 and track it there

**Closed by arjun27** 2018-09-28 09:37 UTC
