### ISSUE TITLE
[vscode] Add new chat provider: Microsoft Teams

### ISSUE THREAD

**Issue by rthiney** [karigari/vscode-chat#113] opened 2018-09-11 01:26 UTC
My chat provider is Microsoft Teams

- Extension Version: 0.5.9
- OS Version: Windows_NT x64 10.0.17744
- VSCode version: 1.27.1

**Comment by arjun27** [comment] 2018-09-28 09:38
thanks @rthiney  - Will close this issue as duplicate of #18 and track it there

**Closed by arjun27** 2018-09-28 09:38 UTC
