### ISSUE TITLE
[vscode] Add new chat provider: Telegram

### ISSUE THREAD

**Issue by ghettopoly** [karigari/vscode-chat#231] opened 2018-10-09 07:30 UTC
My chat provider is Telegram

- Extension Version: 0.6.2
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.28.0

**Comment by arjun27** [comment] 2018-10-09 15:01
closing as duplicate of #68

**Closed by arjun27** 2018-10-09 15:01 UTC
