### ISSUE TITLE
[vscode] Add new chat provider: Telegram

### ISSUE THREAD

**Issue by tangshihua** [karigari/vscode-chat#204] opened 2018-09-29 09:27 UTC
My chat provider is Telegram

- Extension Version: 0.6.2
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:01
closing as duplicate of #68

**Closed by arjun27** 2018-10-09 15:01 UTC
