### ISSUE TITLE
[vscode] Add new chat provider: Skype for Business

### ISSUE THREAD

**Issue by jeremyrcox** [karigari/vscode-chat#126] opened 2018-09-14 17:52 UTC
My chat provider is Skype for Business

- Extension Version: 0.5.9
- OS Version: Darwin x64 17.4.0
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:28
closing as duplicate of #121

**Closed by arjun27** 2018-10-09 15:28 UTC
