### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jeansagi** [karigari/vscode-chat#321] opened 2019-02-11 14:03 UTC
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.11.0`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: 
[karigari.chat-unresponsive.cpuprofile.zip](https://github.com/karigari/vscode-chat/files/2851328/karigari.chat-unresponsive.cpuprofile.zip)

`d:\Perfiles\F00001375\karigari.chat-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment] 2019-04-28 02:58
Duplicate of #291

**Closed by arjun27** 2019-04-28 02:58 UTC
Labels: backlog
