### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by iyashpal** [karigari/vscode-chat#308] opened 2019-02-04 10:24 UTC
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.11.0`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/yashpal/karigari.chat-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

[karigari.chat-unresponsive.cpuprofile.txt](https://github.com/karigari/vscode-chat/files/2827443/karigari.chat-unresponsive.cpuprofile.txt)

**Comment by arjun27** [comment] 2019-04-28 02:58
Duplicate of #291

**Closed by arjun27** 2019-04-28 02:58 UTC
Labels: backlog
