### ISSUE TITLE
[vscode] Add new chat provider: Rocket.Chat

### ISSUE THREAD

**Issue by davie-robertson** [karigari/vscode-chat#171] opened 2018-09-25 12:26 UTC
My chat provider is Rocket.Chat

- Extension Version: 0.6.1
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:04
closing as duplicate of #9

**Closed by arjun27** 2018-10-09 15:04 UTC
