### ISSUE TITLE
[vscode] Add new chat provider: Microsoft teams

### ISSUE THREAD

**Issue by powerserg79** [karigari/vscode-chat#230] opened 2018-10-08 08:00 UTC
My chat provider is microsoft teams

- Extension Version: 0.6.2
- OS Version: Windows_NT x64 10.0.15063
- VSCode version: 1.27.2

**Comment by chase9** [comment] 2018-10-09 14:53
Duplicate of #18

**Closed** 2018-10-09 15:13 UTC
