### ISSUE TITLE
[vscode] Add new chat provider: Microsoft Teams

### ISSUE THREAD

**Issue by mniczyporuk** [karigari/vscode-chat#157] opened 2018-09-22 20:30 UTC
My chat provider is Microsoft Teams

- Extension Version: 0.6.1
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-09-28 09:49
thanks @mniczyporuk  - Will close this issue as duplicate of #18 and track it there

**Closed by arjun27** 2018-09-28 09:49 UTC
