### ISSUE TITLE
[vscode] Add new chat provider: rocket.chat

### ISSUE THREAD

**Issue by mbujold** [karigari/vscode-chat#215] opened 2018-10-03 10:11 UTC
My chat provider is rocket.chat

- Extension Version: 0.6.2
- OS Version: Linux x64 4.15.0-36-generic
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:05
closing as duplicate of #9

**Closed by arjun27** 2018-10-09 15:05 UTC
