### ISSUE TITLE
[vscode] Add new chat provider: MS Office teams

### ISSUE THREAD

**Issue by digvijaymhasaye** [karigari/vscode-chat#208] opened 2018-09-30 10:01 UTC
My chat provider is MS Office teams

- Extension Version: 0.6.2
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:14
duplicate of #18. will track progress there

**Closed by arjun27** 2018-10-09 15:14 UTC
