### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mchtt** [karigari/vscode-chat#338] opened 2019-03-06 19:41 UTC
[karigari.chat-unresponsive.cpuprofile.txt](https://github.com/karigari/vscode-chat/files/2938009/karigari.chat-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.12.0`
- OS Version: `Linux x64 4.20.13-200.fc29.x86_64`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/jean/karigari.chat-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment] 2019-04-28 02:58
Duplicate of #291

**Closed by arjun27** 2019-04-28 02:58 UTC
Labels: backlog
