### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by webdevcrazier** [karigari/vscode-chat#362] opened 2019-04-10 21:19 UTC
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.13.0`
- OS Version: `Linux x64 4.13.0-46-generic`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/developer/karigari.chat-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment] 2019-04-28 02:58
Duplicate of #291

**Closed by arjun27** 2019-04-28 02:58 UTC
