### ISSUE TITLE
Not working on enterprise workspaces

### ISSUE THREAD

**Issue by kalbond** [karigari/vscode-chat#10] opened 2018-06-26 17:35 UTC
I'm using a Mac. When I open slack, I don't get a default channel - just a blank panel with the message box. If I try to change the channel, I get this error 
![screen shot 2018-06-26 at 1 32 39 pm](https://user-images.githubusercontent.com/13543196/41929369-ce229cce-7945-11e8-8f22-5bb16e7b7d70.png)

**Comment by arjun27** [comment] 2018-06-26 17:38
Thanks for reporting. Couple of questions:

- Did you see the list of available channels when you chose the "Slack: Open" command?
- Can you try a restart of the editor and run the "Slack: Open" command?

I'm investigating what could be wrong at my end too. Will keep you posted here

**Comment by kalbond** [comment] 2018-06-26 17:39
@arjun27 

- No, I didn't get an option to select a channel
- Restarted a few times already

Thank you!

**Comment by arjun27** [comment] 2018-06-26 17:53
Thanks, and sorry that you're running into this! I went through the code path, and realized this would happen if the token is incorrect. I should check that internally, and add a helpful message for that case.

Can we do a quick check of the token that you are using? We can run this in the terminal

```
curl https://slack.com/api/auth.test\?token\=YOUR_TOKEN_HERE
```

Going through the code again to see if there's any other possibility

**Comment by kalbond** [comment] 2018-06-26 17:55
Tried it. The response is OK

**Comment by arjun27** [comment] 2018-06-26 18:05
Thanks for your patience, appreciate it. Let me test this more exhaustively, and at the least release a build with better error messages.

**Comment by arjun27** [comment] 2018-06-27 20:42
@kalbond, my suspicion is that this was caused due to a rendering bug and is fixed in https://github.com/karigari/vscode-chat/commit/3f1d69420108d8a1dbcd1ea0803407b8cfc11208. I just published 0.2.1 to the marketplace with the fix.

In case it doesn't work, we have logs to better understand what's happening. These will be accessible as the "Slack Chat" output (cmd + shift + U on macOS). We also have logs on the rendering side, and they can be accessed with the "Open Webview Developer Tools" command (cmd + shift + P).

<img width="552" alt="screen shot 2018-06-28 at 2 06 19 am" src="https://user-images.githubusercontent.com/284612/41998288-093f1782-7a78-11e8-8ba9-412a95297148.png">

Let me know if this fixes the issue for you, or else I'll dig deeper with the new logs.

**Comment by ahgharian** [comment] 2018-06-28 21:49
I'm seeing the same issue. I am on an enterprise Slack so not sure if that changes anything. 
validated my token and it seems to be okay as well.

**Comment by ahgharian** [comment] 2018-06-28 21:54
Just tested it with a free non-enterprise version and it seems to be working.
The issue is with an enterprise workspace.

**Comment by kalbond** [comment] 2018-06-28 21:55
@ahgharian nice find. No wonder I couldn't get it to work.

**Comment by ahgharian** [comment] 2018-07-06 15:43
I haven't played around with Slack tokens at all. I see that you've updated the docs with contribution section, I will try to run this locally and see what I can find. 

Also, folks at Slack are super helpful. Maybe reach out to them? on Twitter or through your workspace?

**Comment by mattd4d** [comment] 2018-07-13 22:35
<img width="854" alt="screen shot 2018-07-13 at 6 29 48 pm" src="https://user-images.githubusercontent.com/8007653/42716690-c832bb40-86ca-11e8-8912-e6e0c28b9553.png">
A couple of us tried to get this setup for our company slack and ran into the same issue. We are not enterprise but we are plus level. I ran through contribution section and this was in the debug console when i ran `>Slack: Open`

The same error shows up in VSCode when I run `>Slack: Change Channel` 
<img width="336" alt="screen shot 2018-07-13 at 6 33 43 pm" src="https://user-images.githubusercontent.com/8007653/42716777-5150f5fe-86cb-11e8-8a36-8e061ec0e8ab.png">

**Comment by arjun27** [comment] 2018-07-14 05:39
Thanks for digging into this @mattd4d. Your logs are very helpful - and are coming from the part where we parse the list of direct message channels. Couple of things I can tell from the logs

- The API call to Slack was successful, so I don't think token or slack channel type was the issue in this particular case
- The error lies in parsing of the response. Specifically, in this case, a direct message channel exists in the response with a user who was not returned in the `users.list` response. Perhaps this is a guest user from a different workspace?

I'll push a new version out today that handles this parsing issue

**Comment by arjun27** [comment] 2018-07-15 13:23
Pushed https://github.com/karigari/vscode-chat/commit/3488321dacd03084e1be4683f4e78f454537a3ef with this fix, and released v0.4.2 on the marketplace

**Comment by arjun27** [comment] 2018-07-21 11:11
Another relevant change: #28 was created for supporting proxy urls and might apply to some of you here. Proxies are supported in v0.4.5 and to set them up, use the `chat.proxyUrl` configuration.

**Comment by ahgharian** [comment] 2018-08-07 22:19
I didn't get into messing around with this but I can say that it's working for me now. 

Thanks, @arjun27 👍

**Comment by mattd4d** [comment] 2018-08-07 22:35
Shoot I kept meaning to test your updates. I can confirm the latest fixes worked for my team as well @arjune27 - great job, thanks!

**Comment by arjun27** [comment] 2018-08-08 07:34
Awesome, thanks for testing it out. I'm going to close this issue for now.

@kalbond - do let me know if it works for you. If not, we'll open a new issue and track it there.

**Closed by arjun27** 2018-08-08 07:34 UTC
Labels: bug
