### ISSUE TITLE
[vscode] Add new chat provider: hangout

### ISSUE THREAD

**Issue by dioscarr** [karigari/vscode-chat#206] opened 2018-09-29 17:01 UTC
My chat provider is hangout

- Extension Version: 0.6.1
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:31
closing as duplicate of #125

**Closed by arjun27** 2018-10-09 15:31 UTC
