### ISSUE TITLE
[vscode] Add new chat provider: microsoft teams

### ISSUE THREAD

**Issue by FrankGorgenyi** [karigari/vscode-chat#150] opened 2018-09-21 18:04 UTC
My chat provider is microsoft teams

- Extension Version: 0.6.0
- OS Version: Windows_NT x64 10.0.18242
- VSCode version: 1.28.0-insider

**Comment by arjun27** [comment] 2018-09-28 09:49
thanks @FrankGorgenyi  - Will close this issue as duplicate of #18 and track it there

**Closed by arjun27** 2018-09-28 09:49 UTC
