### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Logicxcz** [karigari/vscode-chat#295] opened 2019-01-18 02:05 UTC
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.9.2`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/xcz/karigari.chat-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment] 2019-04-28 02:58
Duplicate of #291

**Closed by arjun27** 2019-04-28 02:58 UTC
Labels: backlog
