### ISSUE TITLE
Extension not updating

### ISSUE THREAD

**Issue by mcamou** [karigari/vscode-chat#328] opened 2019-02-22 09:42 UTC
I have the Slack desktop app running. When I read a channel, I would expect the extension's status bar indicator to be updated (probably not immediately, but soon after). I currently have no unread channels on Slack but the extension indicator says 9 new messages. If I click on it, I see unread messages in some channels that are clean on Slack. As an example, the last message on one of those channels is from 2 days ago (and I read it at that time). Even reading it using the extension does not clear the "new" indicator for that channel.

**Comment by sayex** [comment] 2019-03-22 04:59
Same issue except the channel that says I have an unread message it really does not and has not had a message in weeks.

**Comment by arjun27** [comment] 2019-03-22 16:36
Thanks for reporting this @mcamou @sayex. I'm able to reproduce this issue on channels that have thread messages. Reading a thread is not handled getting properly, and so that count is not reduced from the status bar notification. I'm investigating how this can be fixed

**Comment by arjun27** [comment] 2019-06-27 18:35
Marking as a duplicate of #92 and closing this

**Closed by arjun27** 2019-06-27 18:35 UTC
Labels: backlog, bug
