### ISSUE TITLE
[vscode] Add new chat provider: Skype For Business

### ISSUE THREAD

**Issue by vijjusri14** [karigari/vscode-chat#167] opened 2018-09-24 13:36 UTC
My chat provider is Skype For Business

- Extension Version: 0.6.0
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:28
closing as duplicate of #121

**Closed by arjun27** 2018-10-09 15:28 UTC
