### ISSUE TITLE
[vscode] Add new chat provider: Telegram

### ISSUE THREAD

**Issue by Triple-Z** [karigari/vscode-chat#100] opened 2018-09-06 09:55 UTC
My chat provider is Telegram

- Extension Version: 0.5.9
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.26.1

**Comment by arjun27** [comment] 2018-10-09 15:02
closing as duplicate of #68

**Closed by arjun27** 2018-10-09 15:02 UTC
