### ISSUE TITLE
[vscode] Add new chat provider: Mattermost

### ISSUE THREAD

**Issue by Kay-rahan** [karigari/vscode-chat#228] opened 2018-10-07 10:49 UTC
My chat provider is Mattermost

- Extension Version: 0.6.2
- OS Version: Windows, Linux and MacOS
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:03
closing as duplicate of #118

**Closed by arjun27** 2018-10-09 15:03 UTC
