### ISSUE TITLE
[vscode] Add new chat provider: Microsoft Teams

### ISSUE THREAD

**Issue by ericdboyd** [karigari/vscode-chat#225] opened 2018-10-05 16:49 UTC
My chat provider is Microsoft Teams

- Extension Version: 0.6.2
- OS Version: Windows_NT ia32 10.0.17763
- VSCode version: 1.27.2

**Comment by chase9** [comment] 2018-10-09 14:53
Duplicate of #18

**Closed** 2018-10-09 15:13 UTC
