### ISSUE TITLE
[vscode] Add new chat provider: Rocket.Chat

### ISSUE THREAD

**Issue by dg-skolberg** [karigari/vscode-chat#202] opened 2018-09-28 12:18 UTC
My chat provider is Rocket.Chat

- Extension Version: 0.6.2
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.27.1

**Comment by arjun27** [comment] 2018-10-09 15:05
closing as duplicate of #9

**Closed by arjun27** 2018-10-09 15:05 UTC
