### ISSUE TITLE
[vscode] Add new chat provider: Microsoft Teams

### ISSUE THREAD

**Issue by thomasmaurer** [karigari/vscode-chat#117] opened 2018-09-12 15:23 UTC
My chat provider is Microsoft Teams

- Extension Version: 0.5.9
- OS Version: Windows_NT x64 10.0.17758
- VSCode version: 1.28.0-insider

**Comment by arjun27** [comment] 2018-09-28 09:38
thanks @thomasmaurer  - Will close this issue as duplicate of #18 and track it there

**Closed by arjun27** 2018-09-28 09:38 UTC
