### ISSUE TITLE
[vscode] Add new chat provider: Rocket.Chat

### ISSUE THREAD

**Issue by ephillipe** [karigari/vscode-chat#186] opened 2018-09-26 17:44 UTC
My chat provider is Rocket.Chat

- Extension Version: 0.6.1
- OS Version: Linux x64 4.15.0-34-generic
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:04
closing as duplicate of #9

**Closed by arjun27** 2018-10-09 15:04 UTC
