### ISSUE TITLE
[vscode] Add new chat provider: Microsoft Teams

### ISSUE THREAD

**Issue by vicbirky** [karigari/vscode-chat#141] opened 2018-09-20 00:10 UTC
My chat provider is Microsoft Teams

- Extension Version: 0.5.11
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0-insider

**Comment by arjun27** [comment] 2018-09-28 09:38
thanks @vicbirky  - Will close this issue as duplicate of #18 and track it there

**Closed by arjun27** 2018-09-28 09:38 UTC
