### ISSUE TITLE
[vscode] Add new chat provider: microsoft teams

### ISSUE THREAD

**Issue by smokedlinq** [karigari/vscode-chat#184] opened 2018-09-26 15:44 UTC
My chat provider is Microsoft Teams

- Extension Version: 0.6.1
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-09-28 09:31
thanks @smokedlinq. Will close this issue as duplicate of #18 and track it there

**Closed by arjun27** 2018-09-28 09:31 UTC
