### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by antoineol** [karigari/vscode-chat#332] opened 2019-02-25 20:00 UTC
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.12.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

[karigari.chat-unresponsive.cpuprofile.txt](https://github.com/karigari/vscode-chat/files/2902392/karigari.chat-unresponsive.cpuprofile.txt)

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\archi\karigari.chat-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment] 2019-04-28 02:58
Duplicate of #291

**Closed by arjun27** 2019-04-28 02:58 UTC
Labels: backlog
