### ISSUE TITLE
[vscode] Add new chat provider: Microsoft Teams

### ISSUE THREAD

**Issue by MaximCrabbe** [karigari/vscode-chat#95] opened 2018-09-05 08:58 UTC
My chat provider is Microsoft Teams

- Extension Version: 0.5.9
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.26.1

**Comment by arjun27** [comment] 2018-09-28 09:37
thanks @MaximCrabbe  - Will close this issue as duplicate of #18 and track it there

**Closed by arjun27** 2018-09-28 09:37 UTC
