### ISSUE TITLE
[vscode] Add new chat provider: rocket.chat

### ISSUE THREAD

**Issue by D3LT3RONE** [karigari/vscode-chat#170] opened 2018-09-25 10:19 UTC
My chat provider is rocket.chat

- Extension Version: 0.6.1
- OS Version: Windows_NT x64 6.1.7601
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:04
closing as duplicate of #9

**Closed by arjun27** 2018-10-09 15:04 UTC
