### ISSUE TITLE
[vscode] Add new chat provider: telegram

### ISSUE THREAD

**Issue by raynerdsz25** [karigari/vscode-chat#135] opened 2018-09-18 08:35 UTC
My chat provider is telegram

- Extension Version: 0.5.9
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:02
closing as duplicate of #68

**Closed by arjun27** 2018-10-09 15:02 UTC
