### ISSUE TITLE
[vscode] Add new chat provider: skype

### ISSUE THREAD

**Issue by GooseCoder** [karigari/vscode-chat#159] opened 2018-09-23 18:21 UTC
My chat provider is skype

- Extension Version: 0.6.1
- OS Version: Linux x64 4.18.7-100.fc27.x86_64
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:28
closing as duplicate of #121

**Closed as completed by arjun27** 2018-10-09 15:28 UTC
