### ISSUE TITLE
Restrict Slack channels and direct messages to topk

### ISSUE THREAD

**Issue by mmr-infoworks** [karigari/vscode-chat#179] opened 2018-09-26 09:01 UTC
Somewhat related to https://github.com/karigari/vscode-chat/issues/166

Can we restrict the slack channels , DMs to a Most recently used topN list in the slack pane.
<img width="431" alt="slack" src="https://user-images.githubusercontent.com/26870367/46069290-d2c33b80-c198-11e8-915a-623e49506169.png">

Currently all channels , DM list appear on the slack pane . My slack workspace has about 100 + channels and  seems cluttered to have all of them  listed in the slack pane

**Comment by arjun27** [comment] 2018-09-26 09:07
Thanks for sharing this @mmr-infoworks - definitely want to a find a way to fix this and #166. I'm wondering how we can decide on the limit for number of channels to show. How does your default slack client show them?

**Comment by mmr-infoworks** [comment] 2018-09-26 09:36
I use the webapp .
For DMs is the MRU of a top 10 or so
Slack channels is all my subscribed channels . In VSCode Chat , I can see unsubscribed one's too.

an  MRU based on views for both DMs, and channels would be great

**Comment by arjun27** [comment] 2018-09-28 09:08
great, thanks. I'm going to close this as a duplicate of #166, and track this change there

**Closed by arjun27** 2018-09-28 09:08 UTC
