### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by JeronimoHermano** [karigari/vscode-chat#364] opened 2019-04-11 16:35 UTC
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.13.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\jhdra\karigari.chat-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment] 2019-04-28 02:57
Duplicate of #291

**Closed by arjun27** 2019-04-28 02:57 UTC
