### ISSUE TITLE
[vscode] Add new chat provider: Telegram

### ISSUE THREAD

**Issue by Marco87Developer** [karigari/vscode-chat#149] opened 2018-09-20 21:33 UTC
My chat provider is Telegram

- Extension Version: 0.5.11
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.27.2

**Comment by arjun27** [comment] 2018-10-09 15:02
closing as duplicate of #68

**Closed by arjun27** 2018-10-09 15:02 UTC
