### ISSUE TITLE
[vscode] Add new chat provider: Rocket Chat

### ISSUE THREAD

**Issue by jschirrmacher** [karigari/vscode-chat#110] opened 2018-09-10 09:03 UTC
My chat provider is Rocket Chat

- Extension Version: 0.5.9
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.26.1

**Comment by arjun27** [comment] 2018-10-09 15:04
closing as duplicate of #9

**Closed by arjun27** 2018-10-09 15:04 UTC
