### ISSUE TITLE
[vscode] Add new chat provider

### ISSUE THREAD

**Issue by Exspiravit** [karigari/vscode-chat#84] opened 2018-08-31 16:54 UTC
My chat provider is: Telegram

- Extension Version: 0.5.8
- OS Version: Linux x64 4.15.0-33-generic
- VSCode version: 1.26.1

**Comment by mittalyashu** [comment] 2018-08-31 18:15
This request has been made already at https://github.com/karigari/vscode-chat/issues/68

**Comment by arjun27** [comment] 2018-10-09 15:02
closing as duplicate of #68

**Closed by arjun27** 2018-10-09 15:02 UTC
